# Generated by Django 6.0.3 on 2026-04-20 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='User who created the record (alias for created_by)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Created by User'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for pickup location', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup point latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup point longitude', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='radius_km',
            field=models.IntegerField(blank=True, help_text='Service radius in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='base_city',
            field=models.ForeignKey(blank=True, help_text='City where the headquarters is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='api.shipping', verbose_name='Base City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='that created the record'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(help_text='اسم طريقة الدفع بالعربية', max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(help_text='اسم طريقة الدفع بالإنجليزية', max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('payment_type', models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي'), ('wallet', 'محفظة إلكترونية'), ('card', 'بطاقة بنكية'), ('other', 'أخرى')], default='cash', help_text='نوع طريقة الدفع', max_length=20, verbose_name='نوع الدفع')),
                ('gateway_provider', models.CharField(blank=True, help_text='مزود بوابة الدفع (مثل: CIB, BaridiMob)', max_length=50, null=True, verbose_name='مزود البوابة')),
                ('account_name', models.CharField(blank=True, help_text='اسم صاحب الحساب أو المستفيد', max_length=200, null=True, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(blank=True, help_text='رقم الحساب البنكي أو الحساب البريدي الجاري (CCP)', max_length=100, null=True, verbose_name='رقم الحساب/الحساب البريدي الجاري')),
                ('iban', models.CharField(blank=True, help_text='رقم الحساب البنكي الدولي (IBAN)', max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='IBAN غير صالح', regex='^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN')),
                ('instructions_ar', models.TextField(blank=True, help_text='تعليمات الدفع للزبائن بالعربية', null=True, verbose_name='التعليمات بالعربية')),
                ('instructions_en', models.TextField(blank=True, help_text='تعليمات الدفع للزبائن بالإنجليزية', null=True, verbose_name='التعليمات بالإنجليزية')),
                ('icon', models.CharField(blank=True, help_text='كود أيقونة Font Awesome (مثل: fas fa-university)', max_length=100, null=True, verbose_name='الأيقونة')),
                ('logo', models.ImageField(blank=True, help_text='شعار البنك أو خدمة الدفع', max_length=255, null=True, upload_to='payment_methods/logos/', verbose_name='الشعار')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور طريقة الدفع في القائمة', verbose_name='ترتيب الظهور')),
                ('is_active', models.BooleanField(default=True, help_text='هل طريقة الدفع نشطة ومتاحة للزبائن', verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, help_text='طريقة الدفع الافتراضية (واحدة فقط)', verbose_name='افتراضي')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى للمبلغ المسموح بهذه الطريقة', max_digits=12, null=True, verbose_name='الحد الأقصى للمبلغ')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='نسبة الرسوم المضافة للمبلغ (%)', max_digits=5, verbose_name='نسبة الرسوم')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0, help_text='رسوم ثابتة مضافة للمبلغ', max_digits=10, verbose_name='رسوم ثابتة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the payment method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='that created the record')),
                ('created_by_user', models.ForeignKey(blank=True, help_text='User who created the payment method (alias for created_by)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user_payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'api_payment_method',
                'ordering': ['order_index', 'name_ar'],
                'db_tablespace': '',
                'indexes': [models.Index(fields=['is_active'], name='payment_method_is_active_idx'), models.Index(fields=['payment_type'], name='payment_method_type_idx'), models.Index(fields=['order_index'], name='payment_method_order_idx'), models.Index(fields=['is_default'], name='payment_method_default_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_payment_method')],
            },
        ),
        migrations.CreateModel(
            name='ProductImageEnhanced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(help_text='Product image URL', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for SEO and accessibility', max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False, help_text='Mark as main/primary image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_images', to='api.product')),
            ],
            options={
                'db_table': 'api_productimage_enhanced',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['product'], name='api_product_product_b54a9d_idx'), models.Index(fields=['is_main'], name='api_product_is_main_5bcdd4_idx'), models.Index(fields=['sort_order'], name='api_product_sort_or_b3cb29_idx'), models.Index(fields=['created_at'], name='api_product_created_7babf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('config_type', models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('sms', 'SMS'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('security', 'Security'), ('backup', 'Backup'), ('api', 'API'), ('ai', 'AI Services')], max_length=50)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('validation_regex', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='api.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='api_systemc_key_6eff4a_idx'), models.Index(fields=['config_type'], name='api_systemc_config__9e9ae7_idx'), models.Index(fields=['organization'], name='api_systemc_organiz_7335dc_idx'), models.Index(fields=['environment'], name='api_systemc_environ_beb359_idx'), models.Index(fields=['is_public'], name='api_systemc_is_publ_69cadb_idx')],
                'unique_together': {('key', 'organization', 'environment')},
            },
        ),
    ]
