# Generated by Django 6.0.3 on 2026-04-20 09:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_created_by_user_shipping_maps_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Discount value (percentage or amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage only)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='Maximum Discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order value to apply coupon', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='Maximum Order Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to activate coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='Minimum Order Value'),
        ),
        migrations.AlterField(
            model_name='couponcampaign',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)]),
        ),
        migrations.AlterField(
            model_name='couponcampaign',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
        migrations.AlterField(
            model_name='couponcampaign',
            name='total_discount_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)]),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='مبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='actual_demand',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='error_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='predicted_demand',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingengine',
            name='international_shipping',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingengine',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingengine',
            name='raw_material_cost',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingengine',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='average_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage coupons', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to use coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='total_discount_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='home_delivery_price',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup point latitude', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup point longitude', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='radius_km',
            field=models.IntegerField(blank=True, help_text='Service radius in kilometers', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='stop_desk_price',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='cod_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='COD Fee'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='express_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Express Price'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='free_shipping_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Free Shipping Minimum'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='home_delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Home Delivery Price'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='insurance_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Insurance rate as percentage of declared value', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum declared value for this price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight for this price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='pickup_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pickup Point Price'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='stop_desk_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stop Desk Price'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='volume_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume Surcharge (per m³)'),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='weight_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight Surcharge (per kg)'),
        ),
    ]
