# Generated by Django 6.0.3 on 2026-04-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_organization_models'),
        ('api', '0009_add_customersegment_fields'),
    ]

    operations = [
    ]
