# Generated by Django 6.0.3 on 2026-04-11 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260411_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_amount_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_promotion_coupon_usage',
            },
        ),
        migrations.CreateModel(
            name='SmartAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRICE_DROP', 'Price Drop'), ('STOCK_ALERT', 'Stock Alert'), ('NEW_PRODUCT', 'New Product'), ('ORDER_STATUS', 'Order Status'), ('PROMOTION', 'Promotion'), ('CUSTOM', 'Custom')], db_index=True, max_length=50)),
                ('message', models.TextField(help_text='Alert message description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this alert is enabled')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Custom conditions for triggering this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Custom name for this alert', max_length=255)),
                ('last_triggered', models.DateTimeField(blank=True, help_text='When this alert was last triggered', null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0, help_text='Number of times this alert has been triggered')),
            ],
            options={
                'verbose_name': 'Smart Alert',
                'verbose_name_plural': 'Smart Alerts',
                'db_table': 'api_smart_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'كوبون', 'verbose_name_plural': 'كوبونات'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'verbose_name': 'استخدام كوبون', 'verbose_name_plural': 'استخدامات الكوبونات'},
        ),
        migrations.AlterModelOptions(
            name='customersegment',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='api_coupon_valid_f_44111e_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='api_coupon_valid_t_232b2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='api_couponu_coupon__cadded_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='api_couponu_user_id_c33afb_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='api_couponu_order_i_719589_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingmethod',
            name='api_shippin_provide_8534c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingmethod',
            name='api_shippin_service_e92943_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviortracking',
            new_name='api_behavio_session_97a6e6_idx',
            old_name='api_behaviortracking_session_id_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_code_idx',
            old_name='api_coupon_code_f609b1_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_active_idx',
            old_name='api_coupon_is_acti_e05ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='coupon_usage_date_idx',
            old_name='api_couponu_used_at_1603ca_idx',
        ),
        migrations.RenameIndex(
            model_name='customersegment',
            new_name='api_custome_is_acti_2c22bb_idx',
            old_name='api_customersegment_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='customersegment',
            new_name='api_custome_priorit_4ded92_idx',
            old_name='api_customersegment_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_coupon__42ec85_idx',
            old_name='api_order_coupon_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingmethod',
            new_name='shipping_active_idx',
            old_name='api_shippin_is_acti_36298c_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='الفئات التي يمكن تطبيق الكوبون عليها', to='api.category', verbose_name='الفئات المطبقة'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='المنتجات التي يمكن تطبيق الكوبون عليها', to='api.product', verbose_name='المنتجات المطبقة'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ الكوبون', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='وصف مفصل للكوبون وشروطه', null=True, verbose_name='وصف الكوبون'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى لقيمة الطلب لتطبيق الكوبون', max_digits=10, null=True, verbose_name='الحد الأقصى للطلب'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الحد الأدنى لقيمة الطلب لتفعيل الكوبون', max_digits=10, verbose_name='الحد الأدنى للطلب'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, help_text='اسم وصفي للكوبون', max_length=200, null=True, verbose_name='اسم الكوبون'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.IntegerField(default=1, help_text='عدد المرات التي يمكن للمستخدم استخدام الكوبون', verbose_name='حد الاستخدام لكل مستخدم'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, db_column='shipping_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_method_orders', to='api.shippingmethod'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='estimated_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='api.organization'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='رمز فريد للكوبون', max_length=50, unique=True, verbose_name='رمز الكوبون'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', help_text='نوع الخصم: نسبة مئوية أو مبلغ ثابت', max_length=20, verbose_name='نوع الخصم'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='قيمة الخصم (نسبة أو مبلغ)', max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الكوبون نشط ومتاح للاستخدام', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أقصى قيمة للخصم (للنسب المئوية فقط)', max_digits=10, null=True, verbose_name='أقصى خصم'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(blank=True, help_text='الحد الأقصى لعدد مرات الاستخدام', null=True, verbose_name='حد الاستخدام'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='عدد المرات التي تم استخدام الكوبون', verbose_name='مرات الاستخدام'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='تاريخ بداية صلاحية الكوبون', null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الكوبون', null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='api.coupon', verbose_name='الكوبون'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='api.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستخدام'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(blank=True, db_column='wilaya_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='api.shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='material_products', through='api.ProductMaterial', to='api.material'),
        ),
        migrations.AlterField(
            model_name='promotioncoupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotion_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupon_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['used_count'], name='coupon_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupon_usage_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_method'], name='api_order_shippin_7ade3a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['organization'], name='shipping_org_idx'),
        ),
        migrations.AlterModelTable(
            name='couponusage',
            table='api_coupon_usage',
        ),
        migrations.AlterModelTable(
            name='shippingmethod',
            table='api_shipping_method',
        ),
        migrations.AddField(
            model_name='promotioncouponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.promotioncoupon'),
        ),
        migrations.AddField(
            model_name='promotioncouponusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_coupon_usages', to='api.order'),
        ),
        migrations.AddField(
            model_name='promotioncouponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='order_amount_before_discount',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='cod_available',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='coverage_wilayas',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='cutoff_time',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='delivery_days',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='expected_delivery_time',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='insurance_available',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='max_dimensions',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='tracking_available',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='tracking_url_template',
        ),
        migrations.AddIndex(
            model_name='promotioncouponusage',
            index=models.Index(fields=['coupon'], name='api_promoti_coupon__13c446_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncouponusage',
            index=models.Index(fields=['user'], name='api_promoti_user_id_8cb3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncouponusage',
            index=models.Index(fields=['order'], name='api_promoti_order_i_4fe1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncouponusage',
            index=models.Index(fields=['used_at'], name='api_promoti_used_at_4a3995_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotioncouponusage',
            unique_together={('coupon', 'user', 'order')},
        ),
        migrations.AddIndex(
            model_name='smartalert',
            index=models.Index(fields=['user', 'is_active'], name='api_smart_a_user_id_197024_idx'),
        ),
        migrations.AddIndex(
            model_name='smartalert',
            index=models.Index(fields=['type', 'is_active'], name='api_smart_a_type_dafa64_idx'),
        ),
        migrations.AddIndex(
            model_name='smartalert',
            index=models.Index(fields=['created_at'], name='api_smart_a_created_b706d5_idx'),
        ),
    ]
