# Generated by Django 6.0.3 on 2026-04-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_promotioncouponusage_smartalert_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'ordering': ['product', 'material']},
        ),
        migrations.RemoveIndex(
            model_name='productmaterial',
            name='api_product_is_acti_962f42_idx',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this coupon can be applied to', to='api.category', verbose_name='Applicable Categories'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Products this coupon can be applied to', to='api.product', verbose_name='Applicable Products'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Unique coupon code', max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description and terms', null=True, verbose_name='Coupon Description'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='percentage', help_text='Discount type: percentage or fixed', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Discount value (percentage or amount)', max_digits=10, verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the coupon is active and usable', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage only)', max_digits=10, null=True, verbose_name='Maximum Discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order value to apply coupon', max_digits=10, null=True, verbose_name='Maximum Order Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to activate coupon', max_digits=10, verbose_name='Minimum Order Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, help_text='Descriptive name for the coupon', max_length=200, null=True, verbose_name='Coupon Name'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(blank=True, help_text='Maximum number of times coupon can be used', null=True, verbose_name='Usage Limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.IntegerField(blank=True, help_text='Number of times user can use coupon', null=True, verbose_name='Usage Limit Per User'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Number of times coupon has been used', verbose_name='Usage Count'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Coupon validity start date', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Coupon validity end date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_materials', to='api.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilogram'), ('m', 'meter'), ('piece', 'piece'), ('liter', 'liter'), ('meter2', 'square meter')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='products', through='api.ProductMaterial', to='api.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilogram'), ('m', 'meter'), ('piece', 'piece'), ('liter', 'liter'), ('meter2', 'square meter')], default='kg', max_length=20),
        ),
    ]
