# Generated by Django 6.0.3 on 2026-04-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_productmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='criteria_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['status'], name='api_custome_status_9a8d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['last_sync_date'], name='api_custome_last_sy_ccfbea_idx'),
        ),
    ]
