# Generated by Django 6.0.3 on 2026-04-19 07:16

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_customersegment_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegmentuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersegmentuser',
            name='added_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersegmentuser',
            name='engagement_score',
            field=models.IntegerField(default=0),
        ),
    ]
