# Generated by Django 6.0.3 on 2026-04-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_customersegment_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingengine',
            name='currency',
            field=models.CharField(default='DZD', max_length=3),
        ),
        migrations.AddField(
            model_name='pricingengine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingengine',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingengine',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingengine',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customersegmentuser',
            index=models.Index(fields=['joined_at'], name='api_custome_joined__cec618_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegmentuser',
            index=models.Index(fields=['added_by_ai'], name='api_custome_added_b_77b4be_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegmentuser',
            index=models.Index(fields=['engagement_score'], name='api_custome_engagem_71ecb1_idx'),
        ),
    ]
