# Generated by Django 6.0.3 on 2026-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_pricingengine_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order_priority', 'name_ar']},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['order_priority'], name='api_blogcat_order_p_2decda_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['is_featured'], name='api_blogcat_is_feat_584087_idx'),
        ),
    ]
