# Generated by Django 6.0.3 on 2026-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief summary of the blog post', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL to the featured image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_minutes',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When this post is scheduled to be published', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this post is published'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['scheduled_at'], name='api_blogpos_schedul_93e380_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['view_count'], name='api_blogpos_view_co_a38f40_idx'),
        ),
    ]
