# Generated by Django 6.0.3 on 2026-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_professional_blogging_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='related_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['message_type'], name='api_convers_message_077eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['is_read'], name='api_convers_is_read_36349b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['related_project'], name='api_convers_related_bf3cd5_idx'),
        ),
    ]
