# Generated by Django 6.0.3 on 2026-04-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_conversationhistory_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='default_chart_type',
            field=models.CharField(default='line', help_text='Default chart type for analytics', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='layout_json',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced layout configuration for dashboard widgets'),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Primary theme color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='refresh_interval',
            field=models.IntegerField(default=30, help_text='Auto-refresh interval in seconds'),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_notifications',
            field=models.BooleanField(default=True, help_text='Enable/disable dashboard notifications'),
        ),
    ]
