# Generated by Django 6.0.3 on 2026-04-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_dashboardsettings_default_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistsettings',
            name='alert_on_low_stock',
            field=models.BooleanField(default=True, help_text='Alert when wishlist items have low stock'),
        ),
        migrations.AddField(
            model_name='wishlistsettings',
            name='max_items_allowed',
            field=models.IntegerField(default=100, help_text='Maximum number of items allowed in wishlist'),
        ),
        migrations.AddField(
            model_name='wishlistsettings',
            name='notify_on_price_drop',
            field=models.BooleanField(default=True, help_text='Notify when wishlist item price drops'),
        ),
        migrations.AddField(
            model_name='wishlistsettings',
            name='privacy_level',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared', 'Shared')], default='private', help_text='Privacy level for wishlist visibility', max_length=10),
        ),
        migrations.AlterField(
            model_name='wishlistsettings',
            name='share_token',
            field=models.CharField(blank=True, help_text='Unique token for sharing wishlist', max_length=64, null=True, unique=True),
        ),
    ]
