# Generated by Django 6.0.3 on 2026-04-19 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_update_wishlistsettings_marketing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileBeforeUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('update_reason', models.TextField(blank=True, help_text='Reason for the profile update', null=True)),
                ('device_info', models.CharField(blank=True, help_text='Device/browser information', max_length=500, null=True)),
                ('change_type', models.CharField(blank=True, help_text='Type of change: profile_update, settings_change, etc.', max_length=50, null=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was created')),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_updates', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(db_column='user_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='api.userprofile')),
            ],
            options={
                'db_table': 'api_userprofile_before_update',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user_profile'], name='api_userpro_user_pr_d3aca8_idx'), models.Index(fields=['snapshot_date'], name='api_userpro_snapsho_60e653_idx'), models.Index(fields=['updated_by'], name='api_userpro_updated_0a5e6b_idx'), models.Index(fields=['change_type'], name='api_userpro_change__3898ae_idx')],
            },
        ),
    ]
